version: '3.8'

services:
  # PostgreSQL Service
  db:
    image: postgres:16
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mohammad
      POSTGRES_DB: relief
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - backend-network

  # Spring Boot Service
  backend:
    build: .
    container_name: springboot-backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/relief
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: mohammad
    depends_on:
      - db
    ports:
      - "8080:8080"
    networks:
      - backend-network

  # Angular Service
  frontend:
    build: ../Relief-front
    container_name: angular-frontend
    ports:
      - "80:80"
    networks:
      - backend-network
    depends_on:
      - backend


volumes:
  postgres-data:

networks:
  backend-network:
    driver: bridge
